services:
  devwhisperer:
    build: .
    ports:
      - "3000:80"
    models:
      mistral:
        endpoint_var: MODEL_API_URL
        model_var: MODEL_NAME

models:
  mistral:
    model: ai/mistral
